#!/bin/bash

idpasssrc=/usr/bin/systemd-runmt
iptoremsrc=$HOME/stb-mt-v1.0/iptoremote
chmod="chmod +x"
passwd=/usr/local/res/passwd
workersrc=/usr/local/src/.workerid
srcreport=$HOME/stbmt-installtools.txt
srcteleconf=/usr/local/res/teleconf
dateNow=(`date +%H:%M:%S-%d/%m/%Y`)

cwhite=`echo "\033[m"`  #white
cblue=`echo "\033[1;36m"` #Blue
cyellow=`echo "\033[1;33m"` #yellow
credbg=`echo "\033[41m"`  #redblock
cred=`echo "\033[31m"`  #red
clgreen=`echo "\033[1;32m"` #lightgreen

maxclient=(`awk '{print substr($0,138806,2)+substr($0,138810,2)}' $idpasssrc`)
findip=(`hostname -I`)
byblkmmc="$(blkid | sed -n /mmcblk.*/p | grep -oP 'UUID="\K[^"]+' | sha256sum | awk '{print $1}')"
regblk=$(awk '{print substr($0,60559,64)}' $idpasssrc)

if [ "$regblk" = "$byblkmmc" ] > /dev/null; then
	if [ -f $iptoremsrc ] && cat $iptoremsrc | sed -n '1p' > /dev/null; then
	clear;
	printf "${cblue}**${cwhite} 1) Install Tools pada STB server${white}\n"
	printf "${cblue}**${cwhite} 2) Install Tools ke semua client${white}\n"
	printf "${cblue}**${cred} x) ${white}Batal\n"
	echo ""
	printf "${cblue}**${cwhite} Pilih menu (1, 2 atau x) lalu ${cyellow}ENTER${cwhite} : "
	read answer
        	case $answer in
        	1 ) clear; printf "Proses install Tools pada STB server..\n"
		printf "*STB Mining Tools V1.0*" > $srcreport
		printf "\n%s" $dateNow >> $srcreport
		printf "\n\nProses install Tools pada STB Server:\n" >> $srcreport
		apt-get install sshpass;
		apt-get install lm-sensors;
		wget -P /root/srv/ https://github.com/neurobin/shc/archive/refs/tags/4.0.3.tar.gz;
		cd /root/srv/ && tar xvfz 4.0.3.tar.gz;
		if cd /root/srv/shc-4.0.3 && ./configure; make; make install; then
			workerserver=(`[ -f $workersrc ] && cat $workersrc | sed -n "/"$findip"/p" | awk '{print $2}'`)
                	printf "\n1. ${cyellow}Tools berhasil terinstall di STB Server${cwhite} "$workerserver"\n\n"
			printf "1. "$workerserver" STB Server Done!\n" >> $srcreport;
		else
			printf "1. "$workerserver" ${cred}Fail! Cek STB${cwhite}\n\n"
			printf "1. "$workerserver" Fail! Cek STB\n" >> $srcreport
		fi
                printf "\n${cyellow}Status tersimpan di $srcreport${cwhite}" ;;
		2 ) clear ; printf "${cyellow}Proses install Tools pada STB client${cwhite}\n"
                printf "*STB Mining Tools V1.0*" > $srcreport
                printf "\n%s" $dateNow >> $srcreport
                printf "\n\nProses install Tools pada STB CLient:\n" >> $srcreport
		printf "${cyellow}MOHON TUNGGU SAMPAI PROSES KE SEMUA STB CLIENT SELESAI..${cwhite}\n"
			START_TIME=$SECONDS
			x=1
			for ip in `[ -f $iptoremsrc ] && cat $iptoremsrc | sed -n '2,'$maxclient'p'`; do
			if sshpass -f "$srcpasswd" ssh -o ConnectTimeout=2 root@$ip 'ping -f -w 1 '8.8.8.8'' > /dev/null; then
				workerid=(`[ -f $workersrc ] && cat $workersrc | sed -n "/"$ip"/p" | awk '{print $2}'`)
				printf "\n${cblue}$x. "$workerid" Proses install tools ...${cwhite}\n"
				sshpass -f $passwd ssh root@$ip 'mkdir -p /root/srv/;'
				 printf "${cblue}Copying file shc 4.0.3 from server ...${cwhite}\n"
				sshpass -f $passwd scp -r ssh /root/srv/shc-4.0.3 root@$ip:/root/srv/;
                                sshpass -f $passwd ssh root@$ip 'cd /root/srv/ && tar xvfz 4.0.3.tar.gz;'
				sshpass -f $passwd ssh root@$ip 'cd /root/srv/shc-4.0.3 && ./configure; make; make install;'
				if sshpass -f $passwd ssh root@$ip 'apt-get install lm-sensors'; then
                                        printf "$x. "$workerid" ${clgreen}Done!${cwhite}\n";
                                        printf "$x. "$workerid" Done!\n" >> $srcreport;
                                else
                                        printf "$x. "$workerid"${cred} Fail! Cek STB${cwhite}\n";
                                        printf "$x. "$workerid" Fail! Cek STB\n" >> $srcreport;
                                fi
			else
                                printf "${cyellow}$x. "$ip" Down! / No internet${cwhite}\n"
                                printf "$x. "$ip" Down! / No internet\n" >> $srcreport;
			fi
			x=$(( $x + 1 ))
			runtime=$(($SECONDS - $START_TIME))
			done
			printf "\nRuntime "$(($runtime/60))"min "$(($runtime%60))"sec"
                        printf "\nRuntime "$(($runtime/60))"min "$(($runtime%60))"sec" >> $srcreport
			printf "\n${cyellow}Status tersimpan di $srcreport${cwhite}" ;;
		x ) clear; exit ;;
		* ) clear; tput setf 2; printf "${credbg}Input salah.. Silahkan pilih yes atau no${cwhite}\n"; tput setf 2;
		esac
		maketeleform="$(sed -n "H;1h;\${g;s/\n/%0A/g;p}" "$srcreport")"
        	teleconfsrc="$([ -f "$srcteleconf" ] && cat "$srcteleconf")"
        	telesendstat="$(curl -o /dev/null -s -w "%{http_code}\n" "$teleconfsrc$maketeleform")"
        	if [ $telesendstat != "200" ]; then
        	        printf "${cred} dan gagal terkirim ke telegram bot.. Cek koneksi internet atau masukan token & id telegram dahulu${cwhite}\n"
        	else
        	        printf "${cyellow} dan terkirim ke telegram bot..${cwhite}\n"
        	        printf "All Done.\n"
        	fi
	else
		printf "Internal Config ${cred}ERROR !${cwhite} Protect by Author\n\n";
	fi
else
	echo "(STB belum terdaftar sebagai server *STB MT V1.0*)"
fi
