#!/bin/bash

idpasssrc=/usr/bin/systemd-runmt
iptoremsrc=$HOME/stb-mt-v1.0/iptoremote
chmod="chmod +x"
passwd=/usr/local/res/passwd
workersrc=/usr/local/src/.workerid
srcreport=$HOME/stbmt-installccminer.txt

cwhite=`echo "\033[m"`  #white
cblue=`echo "\033[1;36m"` #Blue
cyellow=`echo "\033[1;33m"` #yellow
credbg=`echo "\033[41m"`  #redblock
cred=`echo "\033[31m"`  #red
clgreen=`echo "\033[1;32m"` #lightgreen
srcteleconf=/usr/local/res/teleconf
dateNow=(`date +%H:%M:%S-%d/%m/%Y`)

maxclient=(`awk '{print substr($0,138806,2)+substr($0,138810,2)}' $idpasssrc`)
findip=(`hostname -I`)

byblkmmc="$(blkid | sed -n /mmcblk.*/p | grep -oP 'UUID="\K[^"]+' | sha256sum | awk '{print $1}')"
regblk=$(awk '{print substr($0,60559,64)}' $idpasssrc)

if [ "$regblk" = "$byblkmmc" ] > /dev/null; then
	if [ -f $iptoremsrc ] && cat $iptoremsrc | sed -n '1p' > /dev/null; then
	clear;
	printf "${cblue}**${cwhite} 1) Install CCMINER pada STB server${white}\n"
	printf "${cblue}**${cwhite} 2) Install CCMINER ke semua client${white}\n"
	printf "${cblue}**${cred} x) ${white}Batal\n"
	echo ""
	printf "${cblue}**${cwhite} Pilih menu (1, 2 atau x) lalu ${cyellow}ENTER${cwhite} : "
	read answer
	case $answer in
	1 ) clear; printf "Proses install CCMINER pada STB server. Mohon tunggu ...\n"
		printf "*STB Mining Tools V1.0*" > $srcreport
		printf "\n%s" $dateNow >> $srcreport
		printf "\n\nProses install CCMINER pada STB server:\n" >> $srcreport
		apt update;
		apt upgrade -y;
		apt install software-properties-common;
		apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y;
		apt install git;
                rm -rf /root/ccminer/;
                mkdir -p /root/ccminer/;
                cd root/ccminer/;
		git clone --single-branch -b ARM https://github.com/monkins1010/ccminer.git /root/ccminer/;
		cd /root/ccminer/;
                chmod +x build.sh;
                chmod +x configure.sh;
                chmod +x autogen.sh;
                if ./build.sh; then
		workerserver=(`[ -f $workersrc ] && cat $workersrc | sed -n "/"$findip"/p" | awk '{print $2}'`)
		printf "\n1. ${cyellow}CCMINER berhasil terinstall di STB Server${cwhite} "$workerserver"\n\n"
		printf "1. "$workerserver" STB Server Done!\n" >> $srcreport;
		else
		printf "1. "$workerserver" STB Server Fail!\n" >> $srcreport;
		printf "${cyellow}Status tersimpan di $srcreport${cwhite}"
		fi
		;;
	2 ) clear ; printf "${cyellow}Proses install CCMINER pada STB client${cwhite}\n"
		printf "*STB Mining Tools V1.0*" > $srcreport
		printf "\n%s" $dateNow >> $srcreport
		printf "\n\nProses install CCMINER pada STB client:\n" >> $srcreport
		printf "${cyellow}MOHON TUNGGU SAMPAI PROSES KE SEMUA STB CLIENT SELESAI..${cwhite}\n"
		START_TIME=$SECONDS
		x=1
		for ip in `[ -f $iptoremsrc ] && cat $iptoremsrc | sed -n '2,'$maxclient'p'`; do
			if sshpass -f "$srcpasswd" ssh -o ConnectTimeout=2 root@$ip 'ping -f -w 1 '8.8.8.8'' > /dev/null; then
	                workerid=(`[ -f $workersrc ] && cat $workersrc | sed -n "/"$ip"/p" | awk '{print $2}'`)
				printf "\n${cblue}$x. "$workerid" Proses install ...${cwhite}\n"
				sshpass -f $passwd ssh root@$ip 'apt-get update;'
				sshpass -f $passwd ssh root@$ip 'apt-get upgrade -y;'
                                sshpass -f $passwd ssh root@$ip 'apt-get install software-properties-common;'
                               	sshpass -f $passwd ssh root@$ip 'apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y;'
                                sshpass -f $passwd ssh root@$ip 'apt-get install git;'
                                sshpass -f $passwd ssh root@$ip 'rm -rf /root/ccminer/;'
				printf "${cblue}Copying file ccminer from server ...${cwhite}\n"
                                sshpass -f $passwd scp -r /root/ccminer ssh root@$ip:/root/;
                                sshpass -f $passwd ssh root@$ip 'chmod +x /root/ccminer/build.sh;'
                                sshpass -f $passwd ssh root@$ip 'chmod +x /root/ccminer/configure.sh;'
                                sshpass -f $passwd ssh root@$ip 'chmod +x /root/ccminer/autogen.sh;'
                                if sshpass -f $passwd ssh root@$ip 'cd /root/ccminer/ && ./build.sh;'; then
					printf "$x. "$workerid" ${clgreen}Done!${cwhite}\n";
                                        printf "$x. "$workerid" Done!\n" >> $srcreport;
				else
					printf "$x. "$workerid"${cred} Fail! Cek STB${cwhite}\n";
                                        printf "$x. "$workerid" Fail! Cek STB\n" >> $srcreport;
				fi
			else
				printf "${cyellow}$x. "$ip" Down! / No internet${cwhite}\n"
				printf "$x. "$ip" Down! / No internet\n" >> $srcreport;
                        fi
			x=$(( $x + 1 ))
			runtime=$(($SECONDS - $START_TIME))
		done
                printf "\nRuntime "$(($runtime/60))"min "$(($runtime%60))"sec"
                printf "\nRuntime "$(($runtime/60))"min "$(($runtime%60))"sec" >> $srcreport
		printf "\n${cyellow}Status tersimpan di $srcreport${cwhite}" ;;
	x ) exit ;;
	* ) clear; tput setf 2; printf "${credbg}Input salah.. Silahkan pilih 1, 2 atau x${cwhite}\n"; tput setf 2;
	esac
	maketeleform="$(sed -n "H;1h;\${g;s/\n/%0A/g;p}" "$srcreport")"
	teleconfsrc="$([ -f "$srcteleconf" ] && cat "$srcteleconf")"
	telesendstat="$(curl -o /dev/null -s -w "%{http_code}\n" "$teleconfsrc$maketeleform")"
		if [ $telesendstat != "200" ]; then
			printf "${cred} gagal terkirim ke telegram bot.. Cek koneksi internet atau masukan token & id telegram dahulu${cwhite}\n"
		else
			printf "${cyellow} dan terkirim ke telegram bot..${cwhite}\n"
			printf "All Done.\n"
		fi
	else
		printf "Internal Config ${cred}ERROR !${cwhite} Protect by Author\n\n";
	fi
else
echo "(STB belum terdaftar sebagai server *STB MT V1.0*)"
fi
