#!/bin/bash

usrbindir=/usr/bin
srccross=/usr/bin/ntcross
srcmvcross=/usr/bin/mvntcross
srcmnconf=/usr/bin/mnconfig
srcipserver=/usr/local/src/.workerid

inputip=(`[ -f "$srcmnconf" ] && cat "$srcmnconf" | sed -n '1p' | awk '{print $2}'`)
byblkmmc="$(blkid | sed -n /mmcblk.*/p | grep -oP 'UUID="\K[^"]+' | sha256sum | awk '{print $1}')"
pingserver=(`sed -n '1p' "$srcipserver" | awk '{print $1}'`)
findip=(`hostname -I`)

if grep -s "$byblkmmc" "$srccross" > /dev/null; then
	ping -c2 "$inputip" > /dev/null
	if [ $? != 0 ]; then
		sudo ifconfig eth0 down;
	else
		if [ $findip != $pingserver ]; then
			ping -c2 "$pingserver" > /dev/null
			if [ $? != 0 ]; then
				crontab $srccronclDown
				pgrep ccminer | xargs kill > /dev/null
				mv $srccross $srcmvcross
			else
				mv $srcmvcross $srccross
			fi
		fi
		sleep 3
		sudo ifconfig eth0 up
	fi
else
	echo "(STB client tidak terhubung ke STB server *STB MT V1.0*)"
fi
