#!/bin/bash

mnconfsrc=/usr/bin/mnconfig
mnlog=/usr/local/src/.mnlog
rotmnlog=/usr/local/src/.rotmnlog
automining=/usr/local/src/.auto
workersrc=/usr/local/src/.workerid
srccross=/usr/bin/ntcross

luckpoolwallet=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '/wallet_luckpool:/p' | awk '{print $2}'`)
zergpoolwallet=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '/wallet_zergpool:/p' | awk '{print $2}'`)
coinzergid=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '/wallet_zergpool:/p' | awk '{print $3}'`)
findip=(`hostname -I`)
workerid=(`[ -f $srcmnconf ] && cat $workersrc | sed -n "/"${findip}"/p" | awk '{print $2}'`)
minTemp=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '2p' | awk '{print $2}'`)
maxTemp=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '3p' | awk '{print $2}'`)
currTemp=$(sensors | sed -n '3p' | awk -F'.' '{print substr($1,16)}')

byblkmmc="$(blkid | sed -n /mmcblk.*/p | grep -oP 'UUID="\K[^"]+' | sha256sum | awk '{print $1}')"

if grep -s "$byblkmmc" "$srccross" > /dev/null; then
	pgrep ccminer > /dev/null
	if [ $? -ne 0 ] && [ "$currTemp" -le "$minTemp" ]; then
        	touch $mnlog
        	touch $rotmnlog
		rm -rf $automining
		startmining=(`[ -f $srcmnconf ] && cat $mnconfsrc | sed -n '/mining_pool:/p' | awk '{print $2}'`)
			if [ "$startmining" = 1 ]; then
       				/root/ccminer/ccminer  -a verus  -o stratum+tcp://ap.luckpool.net:3956  -u  $luckpoolwallet.$workerid  -p x  -t 4 >> $mnlog
        		else
                		if [ "$startmining" = 2 ]; then
                        		/root/ccminer/ccminer  -a verus -o stratum+tcp://verushash.asia.mine.zergpool.com:3300 -u $zergpoolwallet -p  c=$coinzergid,mc=VRSC,id=$workerid -t 4 >> $mnlog
                        	else
					if [ "$startmining" = 3 ]; then
						echo "Start MINING Zpool "$walletZpool" id="${workerid}""
                                	fi
                		fi
			fi
	else
        	x=`find ""$mnlog"" -printf "%s"`
        	if [ "$x" -gt  10000 ]; then
               		cp $rotmnlog $mnlog
        	else
                	if [ "$currTemp" -ge "$maxTemp" ]; then
                        	pgrep ccminer | xargs kill
                        	rm -rf $mnlog
                        	rm -rf $rotmnlog
				touch $automining 
                	fi
        	fi
	fi
else
echo "(STB client tidak terhubung ke STB server *STB MT V1.0*)"
fi
